disabled = false
languageCode = "zh"
languageName = "简体中文"
weight = 1
title = "HHR's site"

[params]
  displayName = "简体中文"
  isoCode = "zh-CN"
  rtl = false
  dateFormat = "2006-01-02"
  # logo = "author.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"
